theme: minima

title: PlanExe
description: "PlanExe transforms your idea into a plan."

# Minima specific settings.
minima:
  skin: auto
  social_links:
    - title: PlanExe repository at GitHub
      icon: github
      url: "https://github.com/neoneye/PlanExe"

author:
  name: Simon Strandgaard
  email: neoneye@gmail.com
