remote_theme: jekyll/minima

title: PlanExe
description: "PlanExe: Transform your ideas into actionable plans."

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from

# Minima specific settings.
minima:
  skin: auto
  date_format: "%Y-%m-%d"

minima:
  nav_pages:
    - use-cases.md
    - discord.md
    - github.md

# Minima: show excerpts in the frontpage
show_excerpts: true

author:
  name: Simon Strandgaard
  email: neoneye@gmail.com

exclude:
  - README.md
